version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
